# Generated by Django 5.1.1 on 2024-10-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_item_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('episode_number__isnull', True), ('season_number__isnull', True)), fields=('media_id', 'source', 'media_type'), name='unique_item_without_season_episode'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('episode_number__isnull', True), ('season_number__isnull', False)), fields=('media_id', 'source', 'media_type', 'season_number'), name='unique_item_with_season'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('episode_number__isnull', False), ('season_number__isnull', False)), fields=('media_id', 'source', 'media_type', 'season_number', 'episode_number'), name='unique_item_with_season_episode'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('episode_number__isnull', True), ('media_type', 'season'), ('season_number__isnull', False)), models.Q(('media_type', 'season'), _negated=True), _connector='OR'), name='season_number_required_for_season'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('episode_number__isnull', False), ('media_type', 'episode'), ('season_number__isnull', False)), models.Q(('media_type', 'episode'), _negated=True), _connector='OR'), name='season_and_episode_required_for_episode'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('media_type__in', ['season', 'episode']), _negated=True), ('episode_number__isnull', True), ('season_number__isnull', True)), ('media_type__in', ['season', 'episode']), _connector='OR'), name='no_season_episode_for_other_types'),
        ),
    ]
