# Generated by Django 5.1.4 on 2024-12-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_item_media_id_alter_item_media_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='watch_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='historicalepisode',
            old_name='watch_date',
            new_name='end_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book')], default='movie', max_length=10),
        ),
    ]
