# Generated by Django 5.1.5 on 2025-01-31 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_anime_status_alter_book_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anime',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='basicmedia',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='manga',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tv',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='anime',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='app_anime_unique_item_user'),
        ),
        migrations.AddConstraint(
            model_name='basicmedia',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='app_basicmedia_unique_item_user'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='app_book_unique_item_user'),
        ),
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('related_season', 'item'), name='app_episode_unique_season_item'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='app_game_unique_item_user'),
        ),
        migrations.AddConstraint(
            model_name='manga',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='app_manga_unique_item_user'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='app_movie_unique_item_user'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('related_tv', 'item'), name='app_season_unique_tv_item'),
        ),
        migrations.AddConstraint(
            model_name='tv',
            constraint=models.UniqueConstraint(fields=('item', 'user'), name='app_tv_unique_item_user'),
        ),
    ]
