# Generated by Django 5.1.6 on 2025-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_item_app_item_source_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book')], default='movie', max_length=10),
        ),
    ]
