# Generated by Django 5.2 on 2025-05-25 22:01

from django.db import migrations

def convert_repeats_to_instances(apps, schema_editor):
    Episode = apps.get_model('app', 'Episode')
    HistoricalEpisode = apps.get_model('app', 'HistoricalEpisode')

    episodes_with_repeats = Episode.objects.filter(repeats__gt=0)

    for episode in episodes_with_repeats:
        # Get historical records sorted by history_date (newest first)
        history = HistoricalEpisode.objects.filter(
            id=episode.id
        ).order_by('-history_date')

        # The first record is the current state, so we skip it
        for i, historical_record in enumerate(history[1:episode.repeats + 1], start=1):
            new_episode = Episode(
                item=episode.item,
                related_season=episode.related_season,
                end_date=historical_record.end_date,
                repeats=0
            )
            new_episode.save()

        episode.repeats = 0
        episode.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_historicalanime_progress_changed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='episode',
            name='app_episode_unique_season_item',
        ),
        migrations.RunPython(
            convert_repeats_to_instances,
            reverse_code=migrations.RunPython.noop
        ),
    ]
