# Generated by Django 5.2 on 2025-05-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_anime_repeats_remove_basicmedia_repeats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='basicmedia',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['related_season', 'item__episode_number', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['user', 'item', '-created_at']},
        ),
    ]
