# Generated by Django 5.2 on 2025-06-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_alter_anime_options_alter_basicmedia_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['related_season', 'item__episode_number', '-end_date', '-created_at']},
        ),
    ]
