# Generated by Django 5.2.2 on 2025-10-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_add_runtime_to_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalIdMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id_plex', models.CharField(help_text='Fake TMDB ID from external source', max_length=50)),
                ('external_source', models.CharField(default='plex', help_text='Source of fake ID', max_length=20)),
                ('real_tmdb_id', models.CharField(help_text='Valid TMDB ID that actually exists', max_length=20)),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic')], default='tv', help_text='Type of media being mapped', max_length=10)),
                ('title', models.CharField(help_text='Series/movie title for reference', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External ID Mapping',
                'verbose_name_plural': 'External ID Mappings',
            },
        ),
        migrations.RemoveConstraint(
            model_name='item',
            name='app_item_source_valid',
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(choices=[('tmdb', 'The Movie Database'), ('mal', 'MyAnimeList'), ('mangaupdates', 'MangaUpdates'), ('igdb', 'Internet Game Database'), ('openlibrary', 'Open Library'), ('hardcover', 'Hardcover'), ('comicvine', 'Comic Vine'), ('youtube', 'YouTube'), ('manual', 'Manual')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['tmdb', 'mal', 'mangaupdates', 'igdb', 'openlibrary', 'hardcover', 'comicvine', 'youtube', 'manual'])), name='app_item_source_valid'),
        ),
        migrations.AlterUniqueTogether(
            name='externalidmapping',
            unique_together={('tmdb_id_plex', 'external_source', 'media_type')},
        ),
    ]
