# Generated by Django 5.2.2 on 2025-10-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_item_app_item_media_type_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('media_type', 'episode'), ('source', 'youtube'), ('youtube_video_id__isnull', False)), fields=('youtube_video_id',), name='unique_youtube_video_id_for_youtube_episodes'),
        ),
    ]
