# Generated by Django 5.2.2 on 2025-10-23 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_item_youtube_video_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannelFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='YouTube Channel ID (e.g., UCuAXFkgsw1L7xaCfnd5JJOw)', max_length=100)),
                ('channel_name', models.CharField(blank=True, help_text='Optional channel name for easier identification', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_channel_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Channel Filter',
                'verbose_name_plural': 'YouTube Channel Filters',
                'ordering': ['channel_name', 'channel_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel_id'), name='unique_user_channel_filter')],
            },
        ),
    ]
