# Generated by Django 5.2.2 on 2025-10-24 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_add_youtube_channel_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='season_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
