# Generated by Django 3.2 on 2025-10-30
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_alter_item_season_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="broadcast_time",
            field=models.TimeField(null=True, blank=True, help_text="Hora de emisión local (opcional, solo para filtrar pendientes en Home)."),
        ),
    ]
