# Generated by Django 5.2.2 on 2025-10-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_season_broadcast_time'),
    ]

    operations = [
    ]
