# Generated by Django 5.2.2 on 2025-10-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_sync_historicalseason_broadcast_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseason',
            name='broadcast_time',
            field=models.TimeField(blank=True, help_text='Hora de emisión local (opcional, solo para filtrar pendientes en Home).', null=True),
        ),
    ]
