# Generated by Django 5.2.2 on 2025-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_add_reading_time_to_comic_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_time',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated play time in minutes for all gaming sessions'),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='play_time',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated play time in minutes for all gaming sessions'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated reading time in minutes for all issues read'),
        ),
        migrations.AlterField(
            model_name='historicalcomic',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated reading time in minutes for all issues read'),
        ),
    ]
