# Generated by Django 5.2.2 on 2025-11-22 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_add_play_time_to_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='percentage_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Optional percentage progress (0-100) for tracking game completion', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='percentage_progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Optional percentage progress (0-100) for tracking game completion', validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
