# Generated by Django 5.2.2 on 2025-11-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_game_percentage_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated reading time in minutes for all reading sessions'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='reading_time',
            field=models.PositiveIntegerField(default=0, help_text='Total accumulated reading time in minutes for all reading sessions'),
        ),
    ]
