# Generated by Django 5.2.2 on 2025-11-24 11:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_book_reading_time_historicalbook_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalanime',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.AddField(
            model_name='historicalbasicmedia',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.AddField(
            model_name='historicalcomic',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.AddField(
            model_name='historicalmanga',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.AddField(
            model_name='historicalmovie',
            name='progressed_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='progress'),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(help_text='Playtime in minutes for this session')),
                ('percentage_progress', models.PositiveSmallIntegerField(blank=True, help_text='Optional completion percentage captured during the session', null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the session occurred')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('history', 'Migrated from History')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.game')),
            ],
            options={
                'ordering': ['-session_date', '-id'],
            },
        ),
    ]
