# Generated by Django 5.2.2 on 2025-11-24 14:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_historicalanime_progressed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalseason',
            name='broadcast_time',
            field=models.TimeField(blank=True, help_text='Hora de emisiÃ³n local (opcional, solo para filtrar pendientes en Home).', null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='broadcast_time',
            field=models.TimeField(blank=True, help_text='Hora de emisiÃ³n local (opcional, solo para filtrar pendientes en Home).', null=True),
        ),
        migrations.CreateModel(
            name='BookSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(help_text='Reading time in minutes for this session')),
                ('percentage_progress', models.PositiveSmallIntegerField(blank=True, help_text='Optional reading percentage captured during the session', null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the session occurred')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('history', 'Migrated from History')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.book')),
            ],
            options={
                'ordering': ['-session_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ComicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField(help_text='Reading time in minutes for this session')),
                ('issues_read', models.PositiveIntegerField(default=1, help_text='Number of issues read in this session')),
                ('session_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the session occurred')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('history', 'Migrated from History')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.comic')),
            ],
            options={
                'ordering': ['-session_date', '-id'],
            },
        ),
    ]
