# Generated by Django 5.2.2 on 2025-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_historicalseason_broadcast_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tmdb_id',
            field=models.CharField(blank=True, help_text='TMDB ID for manual TV shows (used for Plex webhook integration)', max_length=20, null=True),
        ),
    ]
