# Generated by Django 5.1.2 on 2024-11-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_last_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, help_text='Token for external webhooks', max_length=32, null=True, unique=True),
        ),
    ]
