# Generated by Django 5.1.2 on 2024-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('season', 'Season'), ('episode', 'Episode'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game')], default='tv', max_length=10),
        ),
    ]
