# Generated by Django 5.1.4 on 2024-12-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_last_search_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='book_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('season', 'Season'), ('episode', 'Episode'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book')], default='tv', max_length=10),
        ),
    ]
