# Generated by Django 5.1.4 on 2024-12-19 12:34

from django.db import migrations, models

def convert_table_to_list(apps, schema_editor):
    User = apps.get_model('users', 'User')
    layout_fields = [
        'anime_layout',
        'book_layout',
        'game_layout',
        'manga_layout',
        'movie_layout',
        'season_layout',
        'tv_layout'
    ]

    # Update all users that have 'table' in any layout field
    for field in layout_fields:
        User.objects.filter(**{field: 'table'}).update(**{field: 'list'})


def reverse_convert_table_to_list(apps, schema_editor):
    User = apps.get_model('users', 'User')
    layout_fields = [
        'anime_layout',
        'book_layout',
        'game_layout',
        'manga_layout',
        'movie_layout',
        'season_layout',
        'tv_layout'
    ]

    # Reverse the operation by converting 'list' back to 'table'
    for field in layout_fields:
        User.objects.filter(**{field: 'list'}).update(**{field: 'table'})


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_anime_enabled_user_book_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anime_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='list', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='list', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20),
        ),
        migrations.RunPython(convert_table_to_list, reverse_convert_table_to_list),
    ]
