# Generated by Django 5.1.4 on 2024-12-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_anime_layout_alter_user_book_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hide_from_search',
            field=models.BooleanField(default=True),
        ),
    ]
