# Generated by Django 5.1.6 on 2025-02-12 08:34

from django.db import migrations, models

def update_list_to_table_layouts(apps, schema_editor):
    """
    Update all user records that have 'list' layout to 'table' for all media types
    """
    User = apps.get_model('users', 'User')  # Adjust 'users' to your actual app name

    # Update all media type layouts from 'list' to 'table'
    layout_fields = [
        'tv_layout',
        'season_layout',
        'movie_layout',
        'anime_layout',
        'manga_layout',
        'game_layout',
        'book_layout'
    ]

    for field in layout_fields:
        User.objects.filter(**{field: 'list'}).update(**{field: 'table'})


def reverse_table_to_list_layouts(apps, schema_editor):
    """
    Reverse migration: change 'table' back to 'list' for all media types
    """
    User = apps.get_model('users', 'User')  # Adjust 'users' to your actual app name

    layout_fields = [
        'tv_layout',
        'season_layout',
        'movie_layout',
        'anime_layout',
        'manga_layout',
        'game_layout',
        'book_layout'
    ]

    for field in layout_fields:
        User.objects.filter(**{field: 'table'}).update(**{field: 'list'})

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_last_search_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anime_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='table', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.RunPython(
            update_list_to_table_layouts,
            reverse_table_to_list_layouts
        ),
    ]
