# Generated by Django 5.1.6 on 2025-02-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_anime_layout_alter_user_book_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='calendar_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=20),
        ),
    ]
