# Generated by Django 5.1.6 on 2025-02-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0019_user_calendar_layout'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'season', 'episode', 'movie', 'anime', 'manga', 'game', 'book'])), name='last_search_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tv_layout__in', ['grid', 'table'])), name='tv_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('season_layout__in', ['grid', 'table'])), name='season_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('movie_layout__in', ['grid', 'table'])), name='movie_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('anime_layout__in', ['grid', 'table'])), name='anime_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('manga_layout__in', ['grid', 'table'])), name='manga_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_layout__in', ['grid', 'table'])), name='game_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('book_layout__in', ['grid', 'table'])), name='book_layout_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('calendar_layout__in', ['grid', 'list'])), name='calendar_layout_valid'),
        ),
    ]
