# Generated by Django 5.1.6 on 2025-03-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0020_user_last_search_type_valid_user_tv_layout_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lists_sort',
            field=models.CharField(choices=[('last_item_added', 'Last Item Added'), ('name', 'Name'), ('items_count', 'Items Count'), ('creation_order', 'Newest First')], default='last_item_added', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('lists_sort__in', ['last_item_added', 'name', 'items_count', 'creation_order'])), name='lists_sort_valid'),
        ),
    ]
