# Generated by Django 5.2.2 on 2025-10-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_add_youtube_fields'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0038_alter_user_home_sort_user_home_sort_valid'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='last_search_type_valid',
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_layout',
            field=models.CharField(choices=[('grid', 'Grid'), ('table', 'Table')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_sort',
            field=models.CharField(choices=[('score', 'Rating'), ('title', 'Title'), ('progress', 'Progress'), ('start_date', 'Start Date'), ('end_date', 'End Date')], default='score', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('youtube', 'YouTube')], default='tv', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'youtube'])), name='last_search_type_valid'),
        ),
    ]
