# Generated by Django 5.2.2 on 2025-10-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_remove_item_app_item_media_type_valid_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0039_add_youtube_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='last_search_type_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_search_type',
            field=models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('youtube', 'YouTube'), ('youtube_video', 'YouTube Video')], default='tv', max_length=15),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('last_search_type__in', ['tv', 'movie', 'anime', 'manga', 'game', 'book', 'comic', 'youtube', 'youtube_video'])), name='last_search_type_valid'),
        ),
    ]
