# Generated by Django 5.2.2 on 2025-11-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_add_play_time_to_game'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0040_remove_user_last_search_type_valid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='tv_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='season_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='movie_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='anime_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='manga_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='game_status_valid',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='book_status_valid',
        ),
        migrations.AlterField(
            model_name='user',
            name='anime_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='book_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='comic_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='game_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='manga_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='movie_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tv_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='youtube_status',
            field=models.CharField(choices=[('All', 'All'), ('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped'), ('Pending', 'Pending')], default='All', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('tv_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Pending'])), name='tv_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('season_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Pending'])), name='season_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('movie_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Pending'])), name='movie_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('anime_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Pending'])), name='anime_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('manga_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Pending'])), name='manga_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('game_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Pending'])), name='game_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('book_status__in', ['All', 'Completed', 'In progress', 'Planning', 'Paused', 'Dropped', 'Pending'])), name='book_status_valid'),
        ),
    ]
