# Generated by Django 5.1.7 on 2025-04-22 15:38

from django.db import migrations

def fix_movie_events(apps, schema_editor):
    Event = apps.get_model('events', 'Event')

    # Get all movie events with episode_number
    movie_events = Event.objects.filter(
        item__media_type='movie',
        episode_number__isnull=False
    )

    # Update episode_number to None
    movie_events.update(episode_number=None)

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_tv_events'),
    ]

    operations = [
        migrations.RunPython(fix_movie_events),
    ]
