# Generated by Django 5.1.7 on 2025-04-22 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_comic_historicalcomic_and_more'),
        ('events', '0010_alter_event_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_item_episode',
        ),
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_item_null_episode',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='episode_number',
            new_name='content_number',
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('item', 'content_number'), name='unique_item_episode'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('content_number__isnull', True)), fields=('item',), name='unique_item_null_episode'),
        ),
    ]
